// <auto-generated />
using System;
using Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(FiapDataContext))]
    partial class FiapDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.CONTATO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DDDId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DDDId");

                    b.ToTable("CONTATO");
                });

            modelBuilder.Entity("Domain.Models.DDD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("DDD");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Codigo = 11,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Codigo = 12,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("fb6710a1-b4f1-4428-9640-062f0a4edab8"),
                            Codigo = 13,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("a9eea613-ed71-4be9-99d6-b7a3220bdfe5"),
                            Codigo = 14,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("1d8e6efa-f843-4fba-8fba-863aab670d59"),
                            Codigo = 15,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("2862c5ff-ff85-4e94-93da-5d3269a96b9c"),
                            Codigo = 16,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("c93eddc8-4753-45be-8822-c86924d88cd9"),
                            Codigo = 17,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("edb50bf2-50be-4425-b170-921e0901fa53"),
                            Codigo = 18,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("b5389950-de9a-47de-8685-b28673d2ba30"),
                            Codigo = 19,
                            Estado = "São Paulo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("54c60e50-fc48-44c7-9f95-c446eaa01916"),
                            Codigo = 21,
                            Estado = "Rio de Janeiro",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("03f1a2f2-a352-4202-9595-b103bad12057"),
                            Codigo = 22,
                            Estado = "Rio de Janeiro",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("6d0ad134-73ac-4934-9071-a76b66cdc9e2"),
                            Codigo = 24,
                            Estado = "Rio de Janeiro",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("7c84538b-f945-43bb-8b51-600c8831e8d7"),
                            Codigo = 27,
                            Estado = "Espírito Santo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("2315103b-3bd8-42af-9ee3-11b82ceab16d"),
                            Codigo = 28,
                            Estado = "Espírito Santo",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("fceaf9ab-cae2-4429-84eb-00516b7155f4"),
                            Codigo = 31,
                            Estado = "Minas Gerais",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("c1b58b0b-4699-472e-a7b6-d681fd9f5624"),
                            Codigo = 32,
                            Estado = "Minas Gerais",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("d1559da8-beea-4f90-b805-b2834237c532"),
                            Codigo = 33,
                            Estado = "Minas Gerais",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("6530270f-c2dd-4200-b6e1-3e6984150873"),
                            Codigo = 34,
                            Estado = "Minas Gerais",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("f012ec0c-68ab-4fac-b633-14bc9418ecf1"),
                            Codigo = 35,
                            Estado = "Minas Gerais",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("8b2143c0-7db0-4319-9d63-893aecbbdc78"),
                            Codigo = 37,
                            Estado = "Minas Gerais",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("d9871204-eb33-4621-9782-9e39e030af52"),
                            Codigo = 38,
                            Estado = "Minas Gerais",
                            Regiao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("8124dbe8-78a9-4d40-92ac-9c0b0fe8cb1e"),
                            Codigo = 41,
                            Estado = "Paraná",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("26302019-4b3c-458c-a9a8-c3bcc99f58a9"),
                            Codigo = 42,
                            Estado = "Paraná",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("9c09b143-59be-442f-b3a1-463fd61fdc31"),
                            Codigo = 43,
                            Estado = "Paraná",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("64a2206f-9dca-4b1e-825c-16ea80b2ce08"),
                            Codigo = 44,
                            Estado = "Paraná",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("075af964-e61d-469d-92d4-a54c0958442c"),
                            Codigo = 45,
                            Estado = "Paraná",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("d54c8bc0-41e0-4365-bb7f-1bb699bad816"),
                            Codigo = 46,
                            Estado = "Paraná",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("d6ce0476-3621-4cf4-b46a-47ae94ffc3f7"),
                            Codigo = 47,
                            Estado = "Santa Catarina",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("5b579462-e132-4d78-9491-6dd17663458a"),
                            Codigo = 48,
                            Estado = "Santa Catarina",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("b63e0c50-77f3-4532-ad77-6ef9fa296e78"),
                            Codigo = 49,
                            Estado = "Santa Catarina",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("9642aed1-d9db-4ef4-8f54-0454e3205328"),
                            Codigo = 51,
                            Estado = "Rio Grande do Sul",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("b7850030-b848-45c0-a89a-7f7273b7452d"),
                            Codigo = 53,
                            Estado = "Rio Grande do Sul",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("04d9cde8-e367-4854-8c8c-fe61df7462c8"),
                            Codigo = 54,
                            Estado = "Rio Grande do Sul",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("d7d845ae-9254-4c2c-bbc0-6b612b6dc781"),
                            Codigo = 55,
                            Estado = "Rio Grande do Sul",
                            Regiao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("f813b723-166c-47c6-bd4a-1b6333273974"),
                            Codigo = 61,
                            Estado = "Distrito Federal",
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("96ee8338-0c3d-423c-8303-9ee16a08a665"),
                            Codigo = 62,
                            Estado = "Goiás",
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("650702c5-9eb0-47ab-91c8-f3b4ace89ce0"),
                            Codigo = 63,
                            Estado = "Tocantins",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("24f6d0d7-600b-4ae8-9343-1309fcbfa5aa"),
                            Codigo = 64,
                            Estado = "Goiás",
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("cfb828bb-eaee-4243-8aed-13e6ef0458f7"),
                            Codigo = 65,
                            Estado = "Mato Grosso",
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("ab4e7d35-0be4-46ba-8711-9b1023ff21d2"),
                            Codigo = 66,
                            Estado = "Mato Grosso",
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("bda41bfe-e9b5-4bba-93c7-60c47a938322"),
                            Codigo = 67,
                            Estado = "Mato Grosso do Sul",
                            Regiao = "Centro-Oeste"
                        },
                        new
                        {
                            Id = new Guid("453572b4-9a00-45bc-9a08-8b4fd9e0e70f"),
                            Codigo = 68,
                            Estado = "Acre",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("c12a95a2-70ad-4482-9552-39ae828e8c0b"),
                            Codigo = 69,
                            Estado = "Rondônia",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("3a44a31b-9e47-4ee1-b911-10fe7bf34d2b"),
                            Codigo = 71,
                            Estado = "Bahia",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("bacef241-268f-46b3-a531-b5eb47121b2f"),
                            Codigo = 73,
                            Estado = "Bahia",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("f4324233-1ba7-4efc-96f4-6f8e43b55404"),
                            Codigo = 74,
                            Estado = "Bahia",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("12a9b2f5-b7c0-4bd1-8e83-3d09d50a0329"),
                            Codigo = 75,
                            Estado = "Bahia",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("a589cd12-8bcc-4631-b29c-d7f2d7b488b8"),
                            Codigo = 77,
                            Estado = "Bahia",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("dd4ee5ec-0b15-47a6-9324-c5e1cf4acb94"),
                            Codigo = 79,
                            Estado = "Sergipe",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("9fde129c-622a-4a37-9fe3-b52c64cb2a6f"),
                            Codigo = 81,
                            Estado = "Pernambuco",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("d6932647-cfe3-4d5d-9da1-fa306a20dbb4"),
                            Codigo = 82,
                            Estado = "Alagoas",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("5432ac85-f7b9-4d07-bf65-dae8dc262177"),
                            Codigo = 83,
                            Estado = "Paraíba",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("9ae73451-b8ef-428b-9102-c26bae7183ce"),
                            Codigo = 84,
                            Estado = "Rio Grande do Norte",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("0418ebf8-99b0-47cd-82aa-f57f227a22be"),
                            Codigo = 85,
                            Estado = "Ceará",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("a11b2629-e02e-4822-94be-6eb94e4e3548"),
                            Codigo = 86,
                            Estado = "Piauí",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("9b12d653-b4f4-4350-bb38-4cfe764ddeb9"),
                            Codigo = 87,
                            Estado = "Pernambuco",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("25c44ca7-daa7-4bbd-920b-c4a2def2adcc"),
                            Codigo = 88,
                            Estado = "Ceará",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("7ce1c6a9-d187-4cb8-8dd6-49788d558ea3"),
                            Codigo = 89,
                            Estado = "Piauí",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("875d3b61-dde6-4299-85ec-7b9efff292f9"),
                            Codigo = 91,
                            Estado = "Pará",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("c7890733-04f6-4e79-8a6f-0186784d7136"),
                            Codigo = 92,
                            Estado = "Amazonas",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("c2038bb9-e32c-48ba-8265-79807167625e"),
                            Codigo = 93,
                            Estado = "Pará",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("b4527afd-3571-495a-98f7-29ba1efb85c6"),
                            Codigo = 94,
                            Estado = "Pará",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("c42e91b8-d801-4243-a915-dda61ce7dbe6"),
                            Codigo = 95,
                            Estado = "Roraima",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("a0769d54-65f3-4acd-826f-83e0384fa400"),
                            Codigo = 96,
                            Estado = "Amapá",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("49ad353b-ea45-430d-a06b-1505dae9d57e"),
                            Codigo = 97,
                            Estado = "Amazonas",
                            Regiao = "Norte"
                        },
                        new
                        {
                            Id = new Guid("dd4dfa12-9d96-4957-8a3e-7df07102ab47"),
                            Codigo = 98,
                            Estado = "Maranhão",
                            Regiao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("1ebba230-7440-422b-860d-c8ade9f2d935"),
                            Codigo = 99,
                            Estado = "Maranhão",
                            Regiao = "Nordeste"
                        });
                });

            modelBuilder.Entity("Domain.Models.CONTATO", b =>
                {
                    b.HasOne("Domain.Models.DDD", "DDD")
                        .WithMany("Contatos")
                        .HasForeignKey("DDDId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DDD");
                });

            modelBuilder.Entity("Domain.Models.DDD", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
