apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cadastroapi-replicaset
  labels:
    app: cadastroapi
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: cadastroapi
  template:
    metadata:
      labels:
        app: cadastroapi
    spec:
      containers:
        - name: cadastroapi
          image: antoniodevio/cadastroapi:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: CI
              value: "false"
            - name: Otel__Endpoint
              value: http://otlp-collector:4317
      restartPolicy: Always
