apiVersion: v1
kind: Service
metadata:
  name: cadastroapi
  labels:
    app: cadastroapi
spec:
  type: NodePort
  ports:
    - port: 8080           
      targetPort: 8080     
      nodePort: 31002      
  selector:
    app: cadastroapi
