apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31007
  selector:
    app: consumer
