apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  containers:
    - name: consumer
      image: antoniodevio/consumer:latest
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: Otel__Endpoint
          value: http://otlp-collector:4317
  restartPolicy: Always
