apiVersion: v1
kind: Service
metadata:
  name: consultaapi
  labels:
    app: consultaapi
spec:
  type: NodePort
  ports:
    - port: 8080           
      targetPort: 8080     
      nodePort: 31004      
  selector:
    app: consultaapi
