apiVersion: v1
kind: Service
metadata:
  name: deletaapi
  labels:
    app: deletaapi
spec:
  type: NodePort
  ports:
    - port: 8080           
      targetPort: 8080     
      nodePort: 31005      
  selector:
    app: deletaapi
