apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
    - image: grafana/grafana-oss:latest
      name: grafana
      ports:
        - containerPort: 3000
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
  volumes:
    - name: grafana-data
      persistentVolumeClaim:
        claimName: grafana-data
  restartPolicy: Always
