apiVersion: v1
kind: Pod
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  containers:
    - args:
        - --path.rootfs=/host
      image: quay.io/prometheus/node-exporter:v1.5.0
      name: node-exporter
      volumeMounts:
        - mountPath: /host/proc
          name: node-exporter-claim0
          readOnly: true
        - mountPath: /host/sys
          name: node-exporter-claim1
          readOnly: true
      ports:
        - containerPort: 9100
          protocol: TCP
  restartPolicy: Always
  volumes:
    - name: node-exporter-claim0
      persistentVolumeClaim:
        claimName: node-exporter-claim0
    - name: node-exporter-claim1
      persistentVolumeClaim:
        claimName: node-exporter-claim1
