apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      annotations:
        description: "Deployment NodeExporter"
      labels:
        app: node-exporter
    spec:
      containers:
        - args:
            - --path.rootfs=/host
          image: quay.io/prometheus/node-exporter:v1.5.0
          name: node-exporter
          volumeMounts:
            - mountPath: /host/proc
              name: node-exporter-claim0
              readOnly: true
            - mountPath: /host/sys
              name: node-exporter-claim1
              readOnly: true
          ports:
            - containerPort: 9100
              protocol: TCP
      volumes:
        - name: node-exporter-claim0
          persistentVolumeClaim:
            claimName: node-exporter-claim0
        - name: node-exporter-claim1
          persistentVolumeClaim:
            claimName: node-exporter-claim1
