apiVersion: v1
kind: Pod
metadata:
  name: otlp-collector
  labels:
    app: otlp-collector
spec:
  containers:
    - args:
        - --config=/etc/otel-collector-config.yml
      image: otel/opentelemetry-collector:0.95.0
      name: otlp-collector
      ports:
        - containerPort: 8888
          protocol: TCP
        - containerPort: 8889
          protocol: TCP
        - containerPort: 13133
          protocol: TCP
        - containerPort: 4317
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/otel-collector-config.yml
          name: otlp-collector-cm0
          subPath: otel-collector-config.yml
  restartPolicy: Always
  volumes:
    - name: otlp-collector-cm0
      configMap:
        items:
          - key: otel-collector-config.yml
            path: otel-collector-config.yml
        name: otlp-collector-cm0
