apiVersion: v1
kind: Service
metadata:
  name: productor
  labels:
    app: productor
spec:
  type: NodePort
  ports:
    - port: 8080           
      targetPort: 8080     
      nodePort: 31006      
  selector:
    app: productor
