apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: productor-replicaset
  labels:
    app: productor
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: productor
  template:
    metadata:
      labels:
        app: productor
    spec:
      containers:
        - name: productor
          image: antoniodevio/produtor:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: Otel__Endpoint
              value: http://otlp-collector:4317
      restartPolicy: Always
