apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - name: "15672"
      port: 15672
      nodePort: 32496
      targetPort: 15672
    - name: "5672"
      port: 5672
      nodePort: 32497
      targetPort: 5672
  selector:
    app: rabbitmq
