apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      annotations:
        description: "Deployment SqlServer"
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
              protocol: TCP
          env:
            - name: SA_PASSWORD
              value: "#sa123456789"
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: sqlserver-data
      volumes:
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: sqlserver-data