apiVersion: v1
kind: Pod
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  containers:
    - name: sqlserver
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
        - containerPort: 1433
          protocol: TCP
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: '#sa123456789'
      volumeMounts:
        - mountPath: /var/opt/mssql
          name: sqlserver-data
  volumes:
    - name: sqlserver-data
      persistentVolumeClaim:
        claimName: sqlserver-data
  restartPolicy: Always
