name: CONSULTA-API Workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test_job:
    name: Executanto Job
    runs-on: ubuntu-latest
    env:
      CI: true
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.passdb }}
        ports:
          - 1433:1433
          
    steps:
    - name: Step 1
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:  
        dotnet-version: '8.0.x'
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:   
        username: 'antoniodevio'
        password: ${{ secrets.DOCKERTOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: DockerfileConsulta
        tags: 'antoniodevio/consultaapi:latest'
        push: true
